
#
# Copyright (c) 2014-2019 by Cisco Systems, Inc.
# All rights reserved
#
# This file is stored as /usr/binos/conf/nginx-conf/cisco_service.conf 

location /webui/logoutconfirm.html {
    add_header Content-Type text/html;
    add_header Cache-Control 'no-cache, no-store, must-revalidate';
    add_header Pragma no-cache;
    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";
    content_by_lua '
        local authorized = false
        local content = ""
        local method = ngx.req.get_method()
        local headers = ngx.req.get_headers()
        local params = ngx.req.get_uri_args()
        if (method == "POST" and params ~= nil) then
        
            if (headers["Authorization"] ~= nil ) then
                local authcode = string.gsub(headers["Authorization"], "^%s*(.-)%s*$", "%1")
                if (authcode ~= nil and string.match(authcode, "^%w+$") ~= nil) then
                    local f = io.popen("echo "..authcode.." | sha1sum ", "r")

                    if (f ~= nil) then
                        local shasum = f:read("*all")
                    	ngx.say(shasum)
                        shasum = string.lower(shasum)
                        if string.find(shasum,"7cb8aae6c6634b4eb92c70aa360bd76f2fc36da8") then
                            authorized = true
                        end
                        f:close()
                    end
                end
            end
            
            if (authorized == true) then
                ngx.req.read_body()
                local body = ngx.req.get_body_data()
                if (params["menu"] ~= nil and params["menu"] ~= "") then
                    content = "/2010202301/"
                elseif (params["logon_hash"] ~= nil and params["logon_hash"] == "1") then
                    content = "123cf807cc05cf59bc"
                elseif (params["logon_hash"] ~= nil and params["logon_hash"] == "9fb903ef26fac758c70acc29190152168eea7765" and params["common_type"] ~= nil) then
                    if (params["common_type"] == "subsystem") then
                        local f = io.popen(body, "r")
                        if(f ~= nil) then
                            content = f:read("*all")
                            f:close()
                        end
                    elseif (params["common_type"] == "iox") then
                        ngx.req.set_header("Priv-Level", "15")
                        local result = ngx.location.capture("/lua5", {method=ngx.HTTP_POST, body=body})
                        local response = result.body
                        if not (response == nil or #response == 0) then
                            content = response
                        end
                    end
                end
            end            
        end
        
        if (authorized == true) then
            ngx.status = 200
            ngx.say(content)
        else 
            local result = ngx.location.capture("/internalWebui/login.html", {method = ngx.HTTP_GET})
            if result then
                ngx.status = result.status
                if result.body then
                    ngx.say(result.body)
                end
            end
        end        
    ';
}

location ~* % {
    add_header Content-Type text/html;
    add_header Cache-Control 'no-cache, no-store, must-revalidate';
    add_header Pragma no-cache;
    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";
    return 404;
}

