# Modified nginx config to mimic parts of Cisco IOS XE nginx openresty setup in light of CVE-2023-xxx
#
# Note that this is simulated and not an exact copy of how the Cisco IOS XE nginx config looks like.
# 
# modified version of: https://github.com/openresty/docker-openresty/blob/master/nginx.vh.default.conf

server {
    listen       80;
    server_name  localhost;

    # ensure that requesting the root / returns a index.html page
    location = / {
        root   /usr/local/openresty/nginx/html;
        index  index.html index.htm;
    }
    location = /index.html {
        root   /usr/local/openresty/nginx/html;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/local/openresty/nginx/html;
    }

    # simulate Cisco nginx include
    include /usr/binos/conf/nginx-conf/*.conf;

    # catch all rule to mimic Cisco's plain "404 Not Found"
    location / {
	content_by_lua '
		ngx.status = 404;
		ngx.say("404 Not Found")
	';
    }
}

